// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from resource and datasource lists.

package schema74

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
)

// Resources returns the list of resources supported by this provider.
func GetResources(_ context.Context) []func() resource.Resource {
	resources := []func() resource.Resource{}
	if config.IsExperimentalEnabled() {
	}
	return resources
}

// DataSources returns the list of data sources supported by this provider.
func GetDataSources(_ context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{}
}
