// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Automatic_Rules_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type AutomaticRulesSettingsResourceModel struct {
	AlertRef                               types.String `tfsdk:"alert_ref" json:"alert_ref,optional,omitempty" `
	AllowAuthTraffic                       types.Bool   `tfsdk:"allow_auth_traffic" json:"allow_auth_traffic,optional,omitempty" `
	AllowConnectionsToDnsResolvers         types.Bool   `tfsdk:"allow_connections_to_dns_resolvers" json:"allow_connections_to_dns_resolvers,optional,omitempty" `
	AllowConnectionsToRemoteDhcpServer     types.Bool   `tfsdk:"allow_connections_to_remote_dhcp_server" json:"allow_connections_to_remote_dhcp_server,optional,omitempty" `
	AllowIcmpTrafficForRouteProbing        types.Bool   `tfsdk:"allow_icmp_traffic_for_route_probing" json:"allow_icmp_traffic_for_route_probing,optional,omitempty" `
	AllowListeningInterfacesToDnsRelayPort types.Bool   `tfsdk:"allow_listening_interfaces_to_dns_relay_port" json:"allow_listening_interfaces_to_dns_relay_port,optional,omitempty" `
	AllowNoNat                             types.Bool   `tfsdk:"allow_no_nat" json:"allow_no_nat,optional,omitempty" `
	LogLevel                               types.String `tfsdk:"log_level" json:"log_level,optional,omitempty" `
	QosClassRef                            types.String `tfsdk:"qos_class_ref" json:"qos_class_ref,optional,omitempty" `
	VpnRef                                 types.String `tfsdk:"vpn_ref" json:"vpn_ref,optional,omitempty" `
}
