// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: SMS_Script_Channel

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type SmsScriptChannelResourceModel struct {
	Account             types.String  `tfsdk:"account" json:"account,optional,omitempty" `
	ConnTimeout         types.Int64   `tfsdk:"conn_timeout" json:"conn_timeout,optional,omitempty" `
	Debug               types.Bool    `tfsdk:"debug" json:"debug,optional,omitempty" `
	Name                types.String  `tfsdk:"name" json:"name,optional,omitempty" `
	Password            types.String  `tfsdk:"password" json:"password,optional,omitempty" `
	ProxyPort           types.Int64   `tfsdk:"proxy_port" json:"proxy_port,optional,omitempty" `
	Rank                types.Float64 `tfsdk:"rank" json:"rank,optional,omitempty" `
	ScriptExecutionPath types.String  `tfsdk:"script_execution_path" json:"script_execution_path,optional,omitempty" `
	ScriptPath          types.String  `tfsdk:"script_path" json:"script_path,optional,omitempty" `
	Timeout             types.Int64   `tfsdk:"timeout" json:"timeout,optional,omitempty" `
}

func (r *SmsScriptChannelResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.String()}
}
