// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Connection_Tracking_Options

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type ConnectionTrackingOptionsResourceModel struct {
	DstLimit        types.Int64  `tfsdk:"dst_limit" json:"dst_limit,optional,omitempty" `
	DstLimitAction  types.String `tfsdk:"dst_limit_action" json:"dst_limit_action,optional,omitempty" `
	MssEnforced     types.Bool   `tfsdk:"mss_enforced" json:"mss_enforced,optional,omitempty" `
	MssEnforcedMax  types.Int64  `tfsdk:"mss_enforced_max" json:"mss_enforced_max,optional,omitempty" `
	MssEnforcedMin  types.Int64  `tfsdk:"mss_enforced_min" json:"mss_enforced_min,optional,omitempty" `
	SrcLimit        types.Int64  `tfsdk:"src_limit" json:"src_limit,optional,omitempty" `
	SrcLimitAction  types.String `tfsdk:"src_limit_action" json:"src_limit_action,optional,omitempty" `
	State           types.String `tfsdk:"state" json:"state,optional,omitempty" `
	SyncConnections types.Bool   `tfsdk:"sync_connections" json:"sync_connections,optional,omitempty" `
	Timeout         types.Int64  `tfsdk:"timeout" json:"timeout,optional,omitempty" `
}
