// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: SAML_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type SamlSettingsResourceModel struct {
	SamlAcsUrl             types.String `tfsdk:"saml_acs_url" json:"saml_acs_url,optional,omitempty" `
	SamlMetadataFile       types.String `tfsdk:"saml_metadata_file" json:"saml_metadata_file,optional,omitempty" `
	SamlMethodRef          types.String `tfsdk:"saml_method_ref" json:"saml_method_ref,optional,omitempty" `
	SamlNameIdPolicyFormat types.String `tfsdk:"saml_name_id_policy_format" json:"saml_name_id_policy_format,optional,omitempty" `
	SamlServiceProviderId  types.String `tfsdk:"saml_service_provider_id" json:"saml_service_provider_id,optional,omitempty" `
	SamlSettingUsage       types.String `tfsdk:"saml_setting_usage" json:"saml_setting_usage,optional,omitempty" `
	SamlTlsCredentialsRef  types.String `tfsdk:"saml_tls_credentials_ref" json:"saml_tls_credentials_ref,optional,omitempty" `
	SamlUserAttribute      types.String `tfsdk:"saml_user_attribute" json:"saml_user_attribute,optional,omitempty" `
}
