// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: API_Client

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type ApiClientResourceModel struct {
	ID                     types.String                                       `tfsdk:"id"`
	AdminDomain            types.String                                       `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
	AllowedToLoginInShared types.Bool                                         `tfsdk:"allowed_to_login_in_shared" json:"allowed_to_login_in_shared,optional,omitempty" `
	Comment                types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	ConsoleSuperuser       types.Bool                                         `tfsdk:"console_superuser" json:"console_superuser,optional,omitempty" `
	Enabled                types.Bool                                         `tfsdk:"enabled" json:"enabled,optional,omitempty" fpro:"enabled"`
	Etag                   types.String                                       `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
	IsUserLocked           types.Bool                                         `tfsdk:"is_user_locked" json:"is_user_locked,optional,omitempty" fpro:"is_user_locked"`
	Key                    types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link                   customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                     customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	Locked                 types.Bool                                         `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
	Name                   types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	Permissions            *AdminPermissionsResourceModel                     `tfsdk:"permissions" json:"permissions,optional,omitempty" `
	ReadOnly               types.Bool                                         `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	Superuser              types.Bool                                         `tfsdk:"superuser" json:"superuser,optional,omitempty" `
	System                 types.Bool                                         `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	SystemKey              types.Int64                                        `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
	Trashed                types.Bool                                         `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
}

func (r *ApiClientResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.String()}
}
