// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Route_Map_Matching_Condition

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type RouteMapMatchingConditionResourceModel struct {
	AccessListRef             types.String `tfsdk:"access_list_ref" json:"access_list_ref,optional,omitempty" `
	ExternalBgpPeerAddressRef types.String `tfsdk:"external_bgp_peer_address_ref" json:"external_bgp_peer_address_ref,optional,omitempty" `
	FwclusterPeerAddressRef   types.String `tfsdk:"fwcluster_peer_address_ref" json:"fwcluster_peer_address_ref,optional,omitempty" `
	Metric                    types.Int64  `tfsdk:"metric" json:"metric,optional,omitempty" `
	NextHopRef                types.String `tfsdk:"next_hop_ref" json:"next_hop_ref,optional,omitempty" `
	Rank                      types.Int64  `tfsdk:"rank" json:"rank,optional,omitempty" `
	Type                      types.String `tfsdk:"type" json:"type,optional,omitempty" `
}
