// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Translation_Value

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type TranslationValueResourceModel struct {
	Element      types.String `tfsdk:"element" json:"element,optional,omitempty" `
	IpDescriptor types.String `tfsdk:"ip_descriptor" json:"ip_descriptor,optional,omitempty" `
	MaxPort      types.Int64  `tfsdk:"max_port" json:"max_port,optional,omitempty" `
	MinPort      types.Int64  `tfsdk:"min_port" json:"min_port,optional,omitempty" `
}
