// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: NAT464_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type Nat464SettingsResourceModel struct {
	ClatLocalIpv6PrefixIp   types.String                 `tfsdk:"clat_local_ipv6_prefix_ip" json:"clat_local_ipv6_prefix_ip,optional,omitempty" `
	ClatLocalIpv6PrefixRef  types.String                 `tfsdk:"clat_local_ipv6_prefix_ref" json:"clat_local_ipv6_prefix_ref,optional,omitempty" `
	ClatRemoteIpv6PrefixIp  types.String                 `tfsdk:"clat_remote_ipv6_prefix_ip" json:"clat_remote_ipv6_prefix_ip,optional,omitempty" `
	ClatRemoteIpv6PrefixRef types.String                 `tfsdk:"clat_remote_ipv6_prefix_ref" json:"clat_remote_ipv6_prefix_ref,optional,omitempty" `
	Mode                    types.String                 `tfsdk:"mode" json:"mode,optional,omitempty" `
	Nat64Ipv6PrefixIp       types.String                 `tfsdk:"nat64_ipv6_prefix_ip" json:"nat64_ipv6_prefix_ip,optional,omitempty" `
	Nat64Ipv6PrefixRef      types.String                 `tfsdk:"nat64_ipv6_prefix_ref" json:"nat64_ipv6_prefix_ref,optional,omitempty" `
	Nat64LocalPoolsRef      *[]types.String              `tfsdk:"nat64_local_pools_ref" json:"nat64_local_pools_ref,optional,omitempty" `
	Nat64Mapping            *[]Nat64MappingResourceModel `tfsdk:"nat64_mapping" json:"nat64_mapping,optional,omitempty" `
	SiitEamIpv6PoolIp       types.String                 `tfsdk:"siit_eam_ipv6_pool_ip" json:"siit_eam_ipv6_pool_ip,optional,omitempty" `
	SiitEamIpv6PoolRef      types.String                 `tfsdk:"siit_eam_ipv6_pool_ref" json:"siit_eam_ipv6_pool_ref,optional,omitempty" `
	SiitEamMapping          *[]SiitMappingResourceModel  `tfsdk:"siit_eam_mapping" json:"siit_eam_mapping,optional,omitempty" `
}
