// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: SSL_VPN_Setting

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type SslVpnSettingResourceModel struct {
	RenegociationTimeout    types.Int64  `tfsdk:"renegociation_timeout" json:"renegociation_timeout,optional,omitempty" `
	Ssl30                   types.Bool   `tfsdk:"ssl_3_0" json:"ssl_3_0,optional,omitempty" `
	Tls13                   types.Bool   `tfsdk:"tls_1_3" json:"tls_1_3,optional,omitempty" `
	Tls10                   types.Bool   `tfsdk:"tls_1_0" json:"tls_1_0,optional,omitempty" `
	Tls11                   types.Bool   `tfsdk:"tls_1_1" json:"tls_1_1,optional,omitempty" `
	Tls12                   types.Bool   `tfsdk:"tls_1_2" json:"tls_1_2,optional,omitempty" `
	TlsCryptographySuiteSet types.String `tfsdk:"tls_cryptography_suite_set" json:"tls_cryptography_suite_set,optional,omitempty" `
}
