// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Abstract_Physical_Interface

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type AbstractPhysicalInterfaceResourceModel struct {
	AdslInterface        *AdslPhysicalInterfaceResourceModel        `tfsdk:"adsl_interface" json:"adsl_interface,optional,omitempty" `
	ModemInterface       *ModemInterfaceResourceModel               `tfsdk:"modem_interface" json:"modem_interface,optional,omitempty" `
	PhysicalInterface    *PhysicalInterfaceResourceModel            `tfsdk:"physical_interface" json:"physical_interface,optional,omitempty" `
	PortGroupInterface   *PortGroupInterfaceResourceModel           `tfsdk:"port_group_interface" json:"port_group_interface,optional,omitempty" `
	SsidInterface        *SsidPhysicalInterfaceResourceModel        `tfsdk:"ssid_interface" json:"ssid_interface,optional,omitempty" `
	SwitchInterfacePort  *SwitchInterfacePortResourceModel          `tfsdk:"switch_interface_port" json:"switch_interface_port,optional,omitempty" `
	TunnelInterface      *TunnelInterfaceResourceModel              `tfsdk:"tunnel_interface" json:"tunnel_interface,optional,omitempty" `
	VirtualVlanInterface *VirtualVlanPhysicalInterfaceResourceModel `tfsdk:"virtual_vlan_interface" json:"virtual_vlan_interface,optional,omitempty" `
	VlanInterface        *VlanPhysicalInterfaceResourceModel        `tfsdk:"vlan_interface" json:"vlan_interface,optional,omitempty" `
	VpnBrokerInterface   *VpnBrokerInterfaceResourceModel           `tfsdk:"vpn_broker_interface" json:"vpn_broker_interface,optional,omitempty" `
	WirelessInterface    *WirelessPhysicalInterfaceResourceModel    `tfsdk:"wireless_interface" json:"wireless_interface,optional,omitempty" `
}
