// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Appliance_Info

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type ApplianceInfoResourceModel struct {
	CloudId                     types.String `tfsdk:"cloud_id" json:"cloud_id,optional,omitempty" `
	CloudType                   types.String `tfsdk:"cloud_type" json:"cloud_type,optional,omitempty" `
	FirstUploadTime             types.Int64  `tfsdk:"first_upload_time" json:"first_upload_time,optional,omitempty" `
	HardwareVersion             types.String `tfsdk:"hardware_version" json:"hardware_version,optional,omitempty" `
	InitialContactTime          types.Int64  `tfsdk:"initial_contact_time" json:"initial_contact_time,optional,omitempty" `
	InitialLicenseRemainingDays types.Int64  `tfsdk:"initial_license_remaining_days" json:"initial_license_remaining_days,optional,omitempty" `
	ProductName                 types.String `tfsdk:"product_name" json:"product_name,optional,omitempty" `
	ProofOfSerial               types.String `tfsdk:"proof_of_serial" json:"proof_of_serial,optional,omitempty" `
	SoftwareFeatures            types.String `tfsdk:"software_features" json:"software_features,optional,omitempty" `
	SoftwareVersion             types.String `tfsdk:"software_version" json:"software_version,optional,omitempty" `
}
