// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Capture_Interface

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type CaptureInterfaceResourceModel struct {
	Address                 types.String                                       `tfsdk:"address" json:"address,optional,omitempty" `
	Comment                 types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	InspectQinq             types.Bool                                         `tfsdk:"inspect_qinq" json:"inspect_qinq,optional,omitempty" `
	InspectUnspecifiedVlans types.Bool                                         `tfsdk:"inspect_unspecified_vlans" json:"inspect_unspecified_vlans,optional,omitempty" `
	Key                     types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link                    customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                      customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	LogicalInterfaceRef     types.String                                       `tfsdk:"logical_interface_ref" json:"logical_interface_ref,optional,omitempty" `
	Name                    types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	NetworkValue            types.String                                       `tfsdk:"network_value" json:"network_value,optional,omitempty" `
	Nicid                   types.String                                       `tfsdk:"nicid" json:"nicid,optional,omitempty" `
	ResetInterfaceNicid     types.Int64                                        `tfsdk:"reset_interface_nicid" json:"reset_interface_nicid,optional,omitempty" `
}

func (r *CaptureInterfaceResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Nicid.IsNull() || r.Nicid.IsUnknown() {
		return nil
	}
	return []string{r.Nicid.String()}
}
