// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: ECA_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type EcaSettingsResourceModel struct {
	EcaClientConfig     types.String                          `tfsdk:"eca_client_config" json:"eca_client_config,optional,omitempty" `
	EcaClientNetworkRef *[]types.String                       `tfsdk:"eca_client_network_ref" json:"eca_client_network_ref,optional,omitempty" `
	EcaServerNetworkRef *[]types.String                       `tfsdk:"eca_server_network_ref" json:"eca_server_network_ref,optional,omitempty" `
	EnabledInterface    *[]EnabledInterfaceEntryResourceModel `tfsdk:"enabled_interface" json:"enabled_interface,optional,omitempty" `
	ListenedZoneRef     *[]types.String                       `tfsdk:"listened_zone_ref" json:"listened_zone_ref,optional,omitempty" `
	ListeningPort       types.Int64                           `tfsdk:"listening_port" json:"listening_port,optional,omitempty" `
}
