// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: DHCP_Client_Configuration

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type DhcpClientConfigurationResourceModel struct {
	DhcpAddInfo              types.Int64     `tfsdk:"dhcp_add_info" json:"dhcp_add_info,optional,omitempty" `
	DhcpClientInterface      *[]types.String `tfsdk:"dhcp_client_interface" json:"dhcp_client_interface,optional,omitempty" `
	DhcpClientMode           types.Int64     `tfsdk:"dhcp_client_mode" json:"dhcp_client_mode,optional,omitempty" `
	DhcpServerRef            *[]types.String `tfsdk:"dhcp_server_ref" json:"dhcp_server_ref,optional,omitempty" `
	ProxyArpAddressList      types.String    `tfsdk:"proxy_arp_address_list" json:"proxy_arp_address_list,optional,omitempty" `
	RestrictedAddressEnabled types.Bool      `tfsdk:"restricted_address_enabled" json:"restricted_address_enabled,optional,omitempty" `
	RestrictedAddressList    types.String    `tfsdk:"restricted_address_list" json:"restricted_address_list,optional,omitempty" `
	UseArpProxyEnabled       types.Bool      `tfsdk:"use_arp_proxy_enabled" json:"use_arp_proxy_enabled,optional,omitempty" `
}
