// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Link_Usage_Profile

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type LinkUsageProfileResourceModel struct {
	ID                             types.String                                       `tfsdk:"id"`
	AdminDomain                    types.String                                       `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
	Comment                        types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	DefaultLinkBalancingPreference types.Int64                                        `tfsdk:"default_link_balancing_preference" json:"default_link_balancing_preference,optional,omitempty" `
	Etag                           types.String                                       `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
	Key                            types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link                           customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	LinkDontDuplicateLinkTypeRef   *[]types.String                                    `tfsdk:"link_dont_duplicate_link_type_ref" json:"link_dont_duplicate_link_type_ref,optional,omitempty" `
	LinkDuplicateQosRef            *[]types.String                                    `tfsdk:"link_duplicate_qos_ref" json:"link_duplicate_qos_ref,optional,omitempty" `
	LinkFecPercentage              types.Int64                                        `tfsdk:"link_fec_percentage" json:"link_fec_percentage,optional,omitempty" `
	LinkFecQosRef                  *[]types.String                                    `tfsdk:"link_fec_qos_ref" json:"link_fec_qos_ref,optional,omitempty" `
	LinkFecThreshold               types.Int64                                        `tfsdk:"link_fec_threshold" json:"link_fec_threshold,optional,omitempty" `
	LinkFecTypeRef                 *[]types.String                                    `tfsdk:"link_fec_type_ref" json:"link_fec_type_ref,optional,omitempty" `
	LinkUsageException             *[]LinkUsageEntryResourceModel                     `tfsdk:"link_usage_exception" json:"link_usage_exception,optional,omitempty" `
	Lk                             customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	Locked                         types.Bool                                         `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
	Name                           types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	ReadOnly                       types.Bool                                         `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	System                         types.Bool                                         `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	SystemKey                      types.Int64                                        `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
	Trashed                        types.Bool                                         `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
}

func (r *LinkUsageProfileResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.String()}
}
