// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Abstract_PA_Parameter_Value_wrapper

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type AbstractPaParameterValueWrapperResourceModel struct {
	BooleanValue             *PaBooleanValueResourceModel             `tfsdk:"boolean_value" json:"boolean_value,optional,omitempty" `
	CheckboxListValue        *PaCheckboxListValueResourceModel        `tfsdk:"checkbox_list_value" json:"checkbox_list_value,optional,omitempty" `
	CheckboxValue            *PaCheckBoxValueResourceModel            `tfsdk:"checkbox_value" json:"checkbox_value,optional,omitempty" `
	HtmlValue                *PaHtmlValueResourceModel                `tfsdk:"html_value" json:"html_value,optional,omitempty" `
	IntegerValue             *PaIntegerValueResourceModel             `tfsdk:"integer_value" json:"integer_value,optional,omitempty" `
	IpAddressValue           *PaIpAddressValueResourceModel           `tfsdk:"ip_address_value" json:"ip_address_value,optional,omitempty" `
	MacroValue               *PaMacroValueResourceModel               `tfsdk:"macro_value" json:"macro_value,optional,omitempty" `
	OrderedListBoxValue      *PaOrderedListBoxValueResourceModel      `tfsdk:"ordered_list_box_value" json:"ordered_list_box_value,optional,omitempty" `
	PaDnsSinkholeList        *PaDnsSinkholeListValueResourceModel     `tfsdk:"pa_dns_sinkhole_list" json:"pa_dns_sinkhole_list,optional,omitempty" `
	PaUrlmatchlist           *PaUrlMatchListValueResourceModel        `tfsdk:"pa_urlmatchlist" json:"pa_urlmatchlist,optional,omitempty" `
	ProxyServiceValue        *PaProxyServiceValueResourceModel        `tfsdk:"proxy_service_value" json:"proxy_service_value,optional,omitempty" `
	SshProfileValue          *PaSshProfileValueResourceModel          `tfsdk:"ssh_profile_value" json:"ssh_profile_value,optional,omitempty" `
	StringValue              *PaStringValueResourceModel              `tfsdk:"string_value" json:"string_value,optional,omitempty" `
	TlsInspectionPolicyValue *PaTlsInspectionPolicyValueResourceModel `tfsdk:"tls_inspection_policy_value" json:"tls_inspection_policy_value,optional,omitempty" `
}
