// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Advanced_Multi-Link_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type AdvancedMultiLinkSettingsResourceModel struct {
	ActivateFailover        types.Int64  `tfsdk:"activate_failover" json:"activate_failover,optional,omitempty" `
	DpdInitialValues        types.String `tfsdk:"dpd_initial_values" json:"dpd_initial_values,optional,omitempty" `
	FailoverInitialValues   types.String `tfsdk:"failover_initial_values" json:"failover_initial_values,optional,omitempty" `
	FailoverPropHigh        types.Int64  `tfsdk:"failover_prop_high" json:"failover_prop_high,optional,omitempty" `
	FailoverThreshold       types.Int64  `tfsdk:"failover_threshold" json:"failover_threshold,optional,omitempty" `
	InTrafficInitialValues  types.String `tfsdk:"in_traffic_initial_values" json:"in_traffic_initial_values,optional,omitempty" `
	LatencyInitialValues    types.String `tfsdk:"latency_initial_values" json:"latency_initial_values,optional,omitempty" `
	MultilinkExtraOptions   types.String `tfsdk:"multilink_extra_options" json:"multilink_extra_options,optional,omitempty" `
	PdrInitialValues        types.String `tfsdk:"pdr_initial_values" json:"pdr_initial_values,optional,omitempty" `
	ProbeThreshold          types.Int64  `tfsdk:"probe_threshold" json:"probe_threshold,optional,omitempty" `
	RemoteloadInitialValues types.String `tfsdk:"remoteload_initial_values" json:"remoteload_initial_values,optional,omitempty" `
	ThroughputInitialValues types.String `tfsdk:"throughput_initial_values" json:"throughput_initial_values,optional,omitempty" `
}
