// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Block_List_Scope

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type BlockListScopeResourceModel struct {
	BlockTraffic    types.Bool                      `tfsdk:"block_traffic" json:"block_traffic,optional,omitempty" `
	DropConnection  types.Bool                      `tfsdk:"drop_connection" json:"drop_connection,optional,omitempty" `
	Duration        types.Int64                     `tfsdk:"duration" json:"duration,optional,omitempty" `
	EndPoint1       *BlockListEndPointResourceModel `tfsdk:"end_point1" json:"end_point1,optional,omitempty" `
	EndPoint2       *BlockListEndPointResourceModel `tfsdk:"end_point2" json:"end_point2,optional,omitempty" `
	IncludeObserver types.Bool                      `tfsdk:"include_observer" json:"include_observer,optional,omitempty" `
	ServiceIpRef    types.String                    `tfsdk:"service_ip_ref" json:"service_ip_ref,optional,omitempty" `
}
