// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: PIM_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type PimSettingsResourceModel struct {
	BsrCandidateInterface *BsrCandidateInterfaceEntryResourceModel               `tfsdk:"bsr_candidate_interface" json:"bsr_candidate_interface,optional,omitempty" `
	BsrPriority           types.Int64                                            `tfsdk:"bsr_priority" json:"bsr_priority,optional,omitempty" `
	MroutePreference      types.String                                           `tfsdk:"mroute_preference" json:"mroute_preference,optional,omitempty" `
	PimProfileRef         types.String                                           `tfsdk:"pim_profile_ref" json:"pim_profile_ref,optional,omitempty" `
	RpCandidateInterface  *RpCandidateInterfaceEntryResourceModel                `tfsdk:"rp_candidate_interface" json:"rp_candidate_interface,optional,omitempty" `
	RpPriority            types.Int64                                            `tfsdk:"rp_priority" json:"rp_priority,optional,omitempty" `
	SmRpCandidateEntry    *[]PimSmBootstrapSettingsRpCandidateEntryResourceModel `tfsdk:"sm_rp_candidate_entry" json:"sm_rp_candidate_entry,optional,omitempty" `
}
