// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Internal_Gateway_Certificate_Request

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type InternalGatewayCertificateRequestResourceModel struct {
	ID                 types.String                                       `tfsdk:"id"`
	FromRef            types.String                                       `tfsdk:"from_ref"`
	Comment            types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	Key                types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	KeyLength          types.Int64                                        `tfsdk:"key_length" json:"key_length,optional,omitempty" `
	Link               customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                 customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	Name               types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	PublicKeyAlgorithm types.String                                       `tfsdk:"public_key_algorithm" json:"public_key_algorithm,optional,omitempty" `
	Request            types.String                                       `tfsdk:"request" json:"request,optional,omitempty" `
	SignatureAlgorithm types.String                                       `tfsdk:"signature_algorithm" json:"signature_algorithm,optional,omitempty" `
}

func (r *InternalGatewayCertificateRequestResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.String()}
}
