// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Engine_Interface_wrapper

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type EngineInterfaceWrapperResourceModel struct {
	CaptureInterface                *CaptureInterfaceResourceModel         `tfsdk:"capture_interface" json:"capture_interface,optional,omitempty" `
	ClusterVirtualInterface         *ClusterInterfaceResourceModel         `tfsdk:"cluster_virtual_interface" json:"cluster_virtual_interface,optional,omitempty" `
	InlineInterface                 *InlineInterfaceResourceModel          `tfsdk:"inline_interface" json:"inline_interface,optional,omitempty" `
	InlineIpsInterface              *InlineIpsInterfaceResourceModel       `tfsdk:"inline_ips_interface" json:"inline_ips_interface,optional,omitempty" `
	InlineL2fwInterface             *InlineL2fwInterfaceResourceModel      `tfsdk:"inline_l2fw_interface" json:"inline_l2fw_interface,optional,omitempty" `
	LoopbackClusterVirtualInterface *LoopbackClusterInterfaceResourceModel `tfsdk:"loopback_cluster_virtual_interface" json:"loopback_cluster_virtual_interface,optional,omitempty" `
	LoopbackNodeDedicatedInterface  *LoopbackNodeInterfaceResourceModel    `tfsdk:"loopback_node_dedicated_interface" json:"loopback_node_dedicated_interface,optional,omitempty" `
	NodeInterface                   *NodeInterfaceResourceModel            `tfsdk:"node_interface" json:"node_interface,optional,omitempty" `
	SingleNodeInterface             *SingleNodeInterfaceResourceModel      `tfsdk:"single_node_interface" json:"single_node_interface,optional,omitempty" `
}
