// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: VSS_Container_Node_ISC_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type VssContainerNodeIscSettingsResourceModel struct {
	ID                types.String                                       `tfsdk:"id"`
	FromRef           types.String                                       `tfsdk:"from_ref"`
	Comment           types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	ContactIp         types.String                                       `tfsdk:"contact_ip" json:"contact_ip,optional,omitempty" `
	IscHypervisor     types.String                                       `tfsdk:"isc_hypervisor" json:"isc_hypervisor,optional,omitempty" `
	Key               types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link              customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	ManagementGateway types.String                                       `tfsdk:"management_gateway" json:"management_gateway,optional,omitempty" `
	ManagementIp      types.String                                       `tfsdk:"management_ip" json:"management_ip,optional,omitempty" `
	ManagementNetmask types.Int64                                        `tfsdk:"management_netmask" json:"management_netmask,optional,omitempty" `
	Name              types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
}

func (r *VssContainerNodeIscSettingsResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.String()}
}
