// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: SNMP_Agent

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type SnmpAgentResourceModel struct {
	ID                          types.String                                       `tfsdk:"id"`
	AdminDomain                 types.String                                       `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
	Comment                     types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	Etag                        types.String                                       `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
	Key                         types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link                        customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                          customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	Locked                      types.Bool                                         `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
	Name                        types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	ReadOnly                    types.Bool                                         `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	SnmpMonitoringContact       types.String                                       `tfsdk:"snmp_monitoring_contact" json:"snmp_monitoring_contact,optional,omitempty" `
	SnmpMonitoringListeningPort types.Int64                                        `tfsdk:"snmp_monitoring_listening_port" json:"snmp_monitoring_listening_port,optional,omitempty" `
	SnmpMonitoringUserName      *[]types.String                                    `tfsdk:"snmp_monitoring_user_name" json:"snmp_monitoring_user_name,optional,omitempty" `
	SnmpTrapDestination         *[]SnmpTrapDestinationResourceModel                `tfsdk:"snmp_trap_destination" json:"snmp_trap_destination,optional,omitempty" `
	SnmpTrapUserName            types.String                                       `tfsdk:"snmp_trap_user_name" json:"snmp_trap_user_name,optional,omitempty" `
	SnmpUserName                *[]SnmpUserResourceModel                           `tfsdk:"snmp_user_name" json:"snmp_user_name,optional,omitempty" `
	SnmpVersion                 types.String                                       `tfsdk:"snmp_version" json:"snmp_version,optional,omitempty" `
	System                      types.Bool                                         `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	SystemKey                   types.Int64                                        `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
	Trashed                     types.Bool                                         `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
}

func (r *SnmpAgentResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.String()}
}
