// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Application_Port

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type ApplicationPortResourceModel struct {
	From        types.Int64  `tfsdk:"from" json:"from,optional,omitempty" `
	MaxVersion  types.String `tfsdk:"max_version" json:"max_version,optional,omitempty" `
	MinVersion  types.String `tfsdk:"min_version" json:"min_version,optional,omitempty" `
	Mode        types.String `tfsdk:"mode" json:"mode,optional,omitempty" `
	ProtocolRef types.String `tfsdk:"protocol_ref" json:"protocol_ref,optional,omitempty" `
	Tls         types.String `tfsdk:"tls" json:"tls,optional,omitempty" `
	To          types.Int64  `tfsdk:"to" json:"to,optional,omitempty" `
}
