// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Load_Balancing_Filter

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type LoadBalancingFilterResourceModel struct {
	Action       types.String `tfsdk:"action" json:"action,optional,omitempty" `
	IgnoreOther  types.Bool   `tfsdk:"ignore_other" json:"ignore_other,optional,omitempty" `
	IpDescriptor types.String `tfsdk:"ip_descriptor" json:"ip_descriptor,optional,omitempty" `
	NatEnforce   types.Bool   `tfsdk:"nat_enforce" json:"nat_enforce,optional,omitempty" `
	Nodeid       types.Int64  `tfsdk:"nodeid" json:"nodeid,optional,omitempty" `
	ReplaceIp    types.String `tfsdk:"replace_ip" json:"replace_ip,optional,omitempty" `
	UseIpsec     types.Bool   `tfsdk:"use_ipsec" json:"use_ipsec,optional,omitempty" `
	UsePorts     types.Bool   `tfsdk:"use_ports" json:"use_ports,optional,omitempty" `
}

func (r *LoadBalancingFilterResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Nodeid.IsNull() || r.Nodeid.IsUnknown() {
		return nil
	}
	return []string{fmt.Sprintf("%d", r.Nodeid.ValueInt64())}
}
