// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Third_Party_Monitoring

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type ThirdPartyMonitoringResourceModel struct {
	Encoding               types.String `tfsdk:"encoding" json:"encoding,optional,omitempty" `
	LoggingProfileRef      types.String `tfsdk:"logging_profile_ref" json:"logging_profile_ref,optional,omitempty" `
	MonitoringLogServerRef types.String `tfsdk:"monitoring_log_server_ref" json:"monitoring_log_server_ref,optional,omitempty" `
	Netflow                types.Bool   `tfsdk:"netflow" json:"netflow,optional,omitempty" `
	ProbingProfileRef      types.String `tfsdk:"probing_profile_ref" json:"probing_profile_ref,optional,omitempty" `
	SnmpTrap               types.Bool   `tfsdk:"snmp_trap" json:"snmp_trap,optional,omitempty" `
	TimeZone               types.String `tfsdk:"time_zone" json:"time_zone,optional,omitempty" `
}
