// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Geolocation

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type GeolocationResourceModel struct {
	ID             types.String                                       `tfsdk:"id"`
	AdminDomain    types.String                                       `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
	City           types.String                                       `tfsdk:"city" json:"city,optional,omitempty" `
	Comment        types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	CountryCode    types.String                                       `tfsdk:"country_code" json:"country_code,optional,omitempty" `
	Element        *[]types.String                                    `tfsdk:"element" json:"element,optional,omitempty" `
	Etag           types.String                                       `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
	Key            types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Latitude       types.Float64                                      `tfsdk:"latitude" json:"latitude,optional,omitempty" `
	Link           customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk             customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	Locked         types.Bool                                         `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
	LogoRef        types.String                                       `tfsdk:"logo_ref" json:"logo_ref,optional,omitempty" `
	Longitude      types.Float64                                      `tfsdk:"longitude" json:"longitude,optional,omitempty" `
	Name           types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	PostalCode     types.String                                       `tfsdk:"postal_code" json:"postal_code,optional,omitempty" `
	ReadOnly       types.Bool                                         `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	Region         types.String                                       `tfsdk:"region" json:"region,optional,omitempty" `
	StreetAddress1 types.String                                       `tfsdk:"street_address1" json:"street_address1,optional,omitempty" `
	StreetAddress2 types.String                                       `tfsdk:"street_address2" json:"street_address2,optional,omitempty" `
	System         types.Bool                                         `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	SystemKey      types.Int64                                        `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
	Trashed        types.Bool                                         `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
}

func (r *GeolocationResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.String()}
}
