// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Routing_Node

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type RoutingNodeResourceModel struct {
	ID                    types.String                                       `tfsdk:"id"`
	FromRef               types.String                                       `tfsdk:"from_ref"`
	Comment               types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	CommunicationMode     types.String                                       `tfsdk:"communication_mode" json:"communication_mode,optional,omitempty" `
	CustomConfiguration   types.String                                       `tfsdk:"custom_configuration" json:"custom_configuration,optional,omitempty" `
	DynamicClassid        types.String                                       `tfsdk:"dynamic_classid" json:"dynamic_classid,optional,omitempty" `
	DynamicIpv6           types.Bool                                         `tfsdk:"dynamic_ipv6" json:"dynamic_ipv6,optional,omitempty" `
	DynamicNicid          types.String                                       `tfsdk:"dynamic_nicid" json:"dynamic_nicid,optional,omitempty" `
	ExcludeFromIpCounting types.Bool                                         `tfsdk:"exclude_from_ip_counting" json:"exclude_from_ip_counting,optional,omitempty" `
	Href                  types.String                                       `tfsdk:"href" json:"href,optional,omitempty" `
	Invalid               types.Bool                                         `tfsdk:"invalid" json:"invalid,optional,omitempty" `
	Ip                    types.String                                       `tfsdk:"ip" json:"ip,optional,omitempty" `
	Key                   types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Level                 types.String                                       `tfsdk:"level" json:"level,optional,omitempty" `
	Link                  customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                    customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	MrouteOnly            types.Bool                                         `tfsdk:"mroute_only" json:"mroute_only,optional,omitempty" `
	Name                  types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	NicId                 types.String                                       `tfsdk:"nic_id" json:"nic_id,optional,omitempty" `
	ProbeEcmp             types.Int64                                        `tfsdk:"probe_ecmp" json:"probe_ecmp,optional,omitempty" `
	ProbeInterval         types.Int64                                        `tfsdk:"probe_interval" json:"probe_interval,optional,omitempty" `
	ProbeIpaddress        types.String                                       `tfsdk:"probe_ipaddress" json:"probe_ipaddress,optional,omitempty" `
	ProbeMetric           types.Int64                                        `tfsdk:"probe_metric" json:"probe_metric,optional,omitempty" `
	ProbeRetryCount       types.Int64                                        `tfsdk:"probe_retry_count" json:"probe_retry_count,optional,omitempty" `
	ProbeTest             types.String                                       `tfsdk:"probe_test" json:"probe_test,optional,omitempty" `
	ReadOnly              types.Bool                                         `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	RelatedElementType    types.String                                       `tfsdk:"related_element_type" json:"related_element_type,optional,omitempty" `
	RoutingNode           *[]RoutingNodeResourceModel                        `tfsdk:"routing_node" json:"routing_node,optional,omitempty" `
	System                types.Bool                                         `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	ToDelete              types.Bool                                         `tfsdk:"to_delete" json:"to_delete,optional,omitempty" `
}
