// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: TACACS_Server

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type TacacsServerResourceModel struct {
	ID                   types.String                                       `tfsdk:"id"`
	Address              types.String                                       `tfsdk:"address" json:"address,optional,omitempty" `
	AdminDomain          types.String                                       `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
	ClearText            types.Bool                                         `tfsdk:"clear_text" json:"clear_text,optional,omitempty" `
	Comment              types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	Etag                 types.String                                       `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
	Ipv6Address          types.String                                       `tfsdk:"ipv6_address" json:"ipv6_address,optional,omitempty" `
	Key                  types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link                 customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                   customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	LocationRef          types.String                                       `tfsdk:"location_ref" json:"location_ref,optional,omitempty" `
	Locked               types.Bool                                         `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
	Name                 types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	Port                 types.Int64                                        `tfsdk:"port" json:"port,optional,omitempty" `
	ProvidedMethod       *[]types.String                                    `tfsdk:"provided_method" json:"provided_method,optional,omitempty" `
	ReadOnly             types.Bool                                         `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	Retries              types.Int64                                        `tfsdk:"retries" json:"retries,optional,omitempty" `
	Secondary            *[]types.String                                    `tfsdk:"secondary" json:"secondary,optional,omitempty" `
	SharedSecret         types.String                                       `tfsdk:"shared_secret" json:"shared_secret,optional,omitempty" `
	System               types.Bool                                         `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	SystemKey            types.Int64                                        `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
	ThirdPartyMonitoring *ThirdPartyMonitoringResourceModel                 `tfsdk:"third_party_monitoring" json:"third_party_monitoring,optional,omitempty" `
	Timeout              types.Int64                                        `tfsdk:"timeout" json:"timeout,optional,omitempty" `
	ToolsProfileRef      types.String                                       `tfsdk:"tools_profile_ref" json:"tools_profile_ref,optional,omitempty" `
	Trashed              types.Bool                                         `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
}

func (r *TacacsServerResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.String()}
}
