// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Dynamic_Routing_Redistribution_Entry

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type DynamicRoutingRedistributionEntryResourceModel struct {
	Enabled                 types.Bool   `tfsdk:"enabled" json:"enabled,optional,omitempty" `
	FilterType              types.String `tfsdk:"filter_type" json:"filter_type,optional,omitempty" `
	Metric                  types.Int64  `tfsdk:"metric" json:"metric,optional,omitempty" `
	MetricType              types.String `tfsdk:"metric_type" json:"metric_type,optional,omitempty" `
	RedistributionFilterRef types.String `tfsdk:"redistribution_filter_ref" json:"redistribution_filter_ref,optional,omitempty" `
	RedistributionRmRef     types.String `tfsdk:"redistribution_rm_ref" json:"redistribution_rm_ref,optional,omitempty" `
	Type                    types.String `tfsdk:"type" json:"type,optional,omitempty" `
}
