// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Community_Access_List_Entry

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type CommunityAccessListEntryResourceModel struct {
	Action    types.String `tfsdk:"action" json:"action,optional,omitempty" `
	Comment   types.String `tfsdk:"comment" json:"comment,optional,omitempty" `
	Community types.String `tfsdk:"community" json:"community,optional,omitempty" `
	Key       types.Int64  `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Name      types.String `tfsdk:"name" json:"name,optional,omitempty" `
}

func (r *CommunityAccessListEntryResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Community.IsNull() || r.Community.IsUnknown() {
		return nil
	}
	return []string{r.Community.String()}
}
