// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Antivirus_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type AntivirusSettingsResourceModel struct {
	AntivirusEnabled          types.Bool   `tfsdk:"antivirus_enabled" json:"antivirus_enabled,optional,omitempty" `
	AntivirusHttpProxyEnabled types.Bool   `tfsdk:"antivirus_http_proxy_enabled" json:"antivirus_http_proxy_enabled,optional,omitempty" `
	AntivirusProxyPassword    types.String `tfsdk:"antivirus_proxy_password" json:"antivirus_proxy_password,optional,omitempty" `
	AntivirusProxyPort        types.Int64  `tfsdk:"antivirus_proxy_port" json:"antivirus_proxy_port,optional,omitempty" `
	AntivirusProxyUser        types.String `tfsdk:"antivirus_proxy_user" json:"antivirus_proxy_user,optional,omitempty" `
	AntivirusUpdate           types.String `tfsdk:"antivirus_update" json:"antivirus_update,optional,omitempty" `
	AntivirusUpdateDay        types.String `tfsdk:"antivirus_update_day" json:"antivirus_update_day,optional,omitempty" `
	AntivirusUpdateTime       types.Int64  `tfsdk:"antivirus_update_time" json:"antivirus_update_time,optional,omitempty" `
	VirusAlert                types.String `tfsdk:"virus_alert" json:"virus_alert,optional,omitempty" `
	VirusLogLevel             types.String `tfsdk:"virus_log_level" json:"virus_log_level,optional,omitempty" `
	VirusMirror               types.String `tfsdk:"virus_mirror" json:"virus_mirror,optional,omitempty" `
}
