// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: NAT_Definition

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type NatDefinitionResourceModel struct {
	Comment          types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	EnabledInterface *[]EnabledInterfaceEntryResourceModel              `tfsdk:"enabled_interface" json:"enabled_interface,optional,omitempty" `
	Key              types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link             customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk               customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	Name             types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	NatType          types.String                                       `tfsdk:"nat_type" json:"nat_type,optional,omitempty" `
	PrivateNeRef     types.String                                       `tfsdk:"private_ne_ref" json:"private_ne_ref,optional,omitempty" `
	PublicIp         types.String                                       `tfsdk:"public_ip" json:"public_ip,optional,omitempty" `
	PublicNeRef      types.String                                       `tfsdk:"public_ne_ref" json:"public_ne_ref,optional,omitempty" `
	ServiceRef       *[]types.String                                    `tfsdk:"service_ref" json:"service_ref,optional,omitempty" `
}

func (r *NatDefinitionResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.String()}
}
