// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: BGP_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type BgpSettingsResourceModel struct {
	AnnouncedNeSetting *[]BgpAnnouncedNetworkAssociationResourceModel `tfsdk:"announced_ne_setting" json:"announced_ne_setting,optional,omitempty" `
	BgpAsRef           types.String                                   `tfsdk:"bgp_as_ref" json:"bgp_as_ref,optional,omitempty" `
	BgpProfileRef      types.String                                   `tfsdk:"bgp_profile_ref" json:"bgp_profile_ref,optional,omitempty" `
	BmpRouterId        types.String                                   `tfsdk:"bmp_router_id" json:"bmp_router_id,optional,omitempty" `
	BmpRouterIdType    types.String                                   `tfsdk:"bmp_router_id_type" json:"bmp_router_id_type,optional,omitempty" `
	Enabled            types.Bool                                     `tfsdk:"enabled" json:"enabled,optional,omitempty" `
	RouterId           types.String                                   `tfsdk:"router_id" json:"router_id,optional,omitempty" `
}
