// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: OSPFv2_Profile

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type Ospfv2ProfileResourceModel struct {
	ID                  types.String                                       `tfsdk:"id"`
	AdminDomain         types.String                                       `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
	Comment             types.String                                       `tfsdk:"comment" json:"comment,optional,omitempty" `
	DefaultMetric       types.Int64                                        `tfsdk:"default_metric" json:"default_metric,optional,omitempty" `
	DomainSettingsRef   types.String                                       `tfsdk:"domain_settings_ref" json:"domain_settings_ref,optional,omitempty" `
	Etag                types.String                                       `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
	ExternalDistance    types.Int64                                        `tfsdk:"external_distance" json:"external_distance,optional,omitempty" `
	InterDistance       types.Int64                                        `tfsdk:"inter_distance" json:"inter_distance,optional,omitempty" `
	IntraDistance       types.Int64                                        `tfsdk:"intra_distance" json:"intra_distance,optional,omitempty" `
	Key                 types.Int64                                        `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
	Link                customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"-" json:"link,optional,omitempty" fpro:"link"`
	Lk                  customfield.Map[types.String]                      `tfsdk:"link" json:"-" `
	Locked              types.Bool                                         `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
	Name                types.String                                       `tfsdk:"name" json:"name,optional,omitempty" `
	ReadOnly            types.Bool                                         `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
	RedistributionEntry *[]DynamicRoutingRedistributionEntryResourceModel  `tfsdk:"redistribution_entry" json:"redistribution_entry,optional,omitempty" `
	System              types.Bool                                         `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
	SystemKey           types.Int64                                        `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
	Trashed             types.Bool                                         `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
}

func (r *Ospfv2ProfileResourceModel) GetSliceIds(ctx context.Context) []string {
	if r.Name.IsNull() || r.Name.IsUnknown() {
		return nil
	}
	return []string{r.Name.String()}
}
