// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Elasticsearch_Authentication_Settings

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type ElasticsearchAuthenticationSettingsResourceModel struct {
	ApiKey         types.String `tfsdk:"api_key" json:"api_key,optional,omitempty" `
	Login          types.String `tfsdk:"login" json:"login,optional,omitempty" `
	Method         types.String `tfsdk:"method" json:"method,optional,omitempty" `
	Password       types.String `tfsdk:"password" json:"password,optional,omitempty" `
	TlsCredentials types.String `tfsdk:"tls_credentials" json:"tls_credentials,optional,omitempty" `
}
