// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: User_Response_Entry

package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ = fmt.Sprintf
var _ = context.Background()

type UserResponseEntryResourceModel struct {
	ID                  types.String `tfsdk:"id"`
	Reason              types.String `tfsdk:"reason" json:"reason,optional,omitempty" `
	Redirect            types.String `tfsdk:"redirect" json:"redirect,optional,omitempty" `
	Type                types.String `tfsdk:"type" json:"type,optional,omitempty" `
	UserResponseMessage types.String `tfsdk:"user_response_message" json:"user_response_message,optional,omitempty" `
	UserResponseText    types.String `tfsdk:"user_response_text" json:"user_response_text,optional,omitempty" `
	UserResponseTitle   types.String `tfsdk:"user_response_title" json:"user_response_title,optional,omitempty" `
}
