// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: RPC_Service_Group
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &RpcServiceGroupResource{}
var _ resource.ResourceWithImportState = &RpcServiceGroupResource{}
var _ context.Context = context.Background()

// RpcServiceGroupResource defines the resource implementation.
type RpcServiceGroupResource struct {
	smcresource.ResourceBase[RpcServiceGroupResourceModel]
}

// Schema defines the schema for the RpcServiceGroup resource.
func (r *RpcServiceGroupResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a SUN-RPC Service Group, which is used to group a list of SUN-RPC Services. It can contain both individual SUN-RPC Services and other Service Groups.",
		Attributes:  GetRpcServiceGroupSchemaAttributes(ctx),
		Blocks:      GetRpcServiceGroupSchemaBlocks(ctx),
	} // schema

}

// NewRpcServiceGroupResource creates a new instance of the RpcServiceGroup resource.
func NewRpcServiceGroupResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing RpcServiceGroup resource")
	r := &RpcServiceGroupResource{
		ResourceBase: smcresource.ResourceBase[RpcServiceGroupResourceModel]{
			ResourceType:  "rpc_service_group",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
