// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: IPS_Template_Policy
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &IpsTemplatePolicyResource{}
var _ resource.ResourceWithImportState = &IpsTemplatePolicyResource{}
var _ context.Context = context.Background()

// IpsTemplatePolicyResource defines the resource implementation.
type IpsTemplatePolicyResource struct {
	smcresource.ResourceBase[IpsTemplatePolicyResourceModel]
}

// Schema defines the schema for the IpsTemplatePolicy resource.
func (r *IpsTemplatePolicyResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an IPS Template Policy, which is used to define a set of rules and insert points that can be inherited by other policies or template policies.",
		Attributes:  GetIpsTemplatePolicySchemaAttributes(ctx),
		Blocks:      GetIpsTemplatePolicySchemaBlocks(ctx),
	} // schema

}

// NewIpsTemplatePolicyResource creates a new instance of the IpsTemplatePolicy resource.
func NewIpsTemplatePolicyResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing IpsTemplatePolicy resource")
	r := &IpsTemplatePolicyResource{
		ResourceBase: smcresource.ResourceBase[IpsTemplatePolicyResourceModel]{
			ResourceType:  "ips_template_policy",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
