// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: ECA_Application_Situation
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &EcaApplicationSituationResource{}
var _ resource.ResourceWithImportState = &EcaApplicationSituationResource{}
var _ context.Context = context.Background()

// EcaApplicationSituationResource defines the resource implementation.
type EcaApplicationSituationResource struct {
	smcresource.ResourceBase[EcaApplicationSituationResourceModel]
}

// Schema defines the schema for the EcaApplicationSituation resource.
func (r *EcaApplicationSituationResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an ECA Application Situation, which is used for managing ECA applications and their associated executable files.",
		Attributes:  GetEcaApplicationSituationSchemaAttributes(ctx),
		Blocks:      GetEcaApplicationSituationSchemaBlocks(ctx),
	} // schema

}

// NewEcaApplicationSituationResource creates a new instance of the EcaApplicationSituation resource.
func NewEcaApplicationSituationResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing EcaApplicationSituation resource")
	r := &EcaApplicationSituationResource{
		ResourceBase: smcresource.ResourceBase[EcaApplicationSituationResourceModel]{
			ResourceType:  "ei_application_situation",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
