// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Certificate_Revocation_Fetcher_Task
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &CertificateRevocationFetcherTaskResource{}
var _ resource.ResourceWithImportState = &CertificateRevocationFetcherTaskResource{}
var _ context.Context = context.Background()

// CertificateRevocationFetcherTaskResource defines the resource implementation.
type CertificateRevocationFetcherTaskResource struct {
	smcresource.ResourceBase[CertificateRevocationFetcherTaskResourceModel]
}

// Schema defines the schema for the CertificateRevocationFetcherTask resource.
func (r *CertificateRevocationFetcherTaskResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Certificate Revocation Fetcher Task, which is used to fetch and update certificate revocation lists in the system. It is a type of system task that can be scheduled and executed to ensure that the certificate revocation information is current.",
		Attributes:  GetCertificateRevocationFetcherTaskSchemaAttributes(ctx),
		Blocks:      GetCertificateRevocationFetcherTaskSchemaBlocks(ctx),
	} // schema

}

// NewCertificateRevocationFetcherTaskResource creates a new instance of the CertificateRevocationFetcherTask resource.
func NewCertificateRevocationFetcherTaskResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing CertificateRevocationFetcherTask resource")
	r := &CertificateRevocationFetcherTaskResource{
		ResourceBase: smcresource.ResourceBase[CertificateRevocationFetcherTaskResourceModel]{
			ResourceType:  "fetch_certificate_revocation_task",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
