// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: DHCP_Server
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &DhcpServerResource{}
var _ resource.ResourceWithImportState = &DhcpServerResource{}
var _ context.Context = context.Background()

// DhcpServerResource defines the resource implementation.
type DhcpServerResource struct {
	smcresource.ResourceBase[DhcpServerResourceModel]
}

// Schema defines the schema for the DhcpServer resource.
func (r *DhcpServerResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a DHCP (Dynamic Host Configuration Protocol) Server. A protocol for dynamically assigning IP addresses and other network information to an interface, based on BOOTP. A device on a network with no network information can broadcast a request for an IP address, subnet mask, default gateway and other information from a DHCP server on that same network. DHCP is defined in RFC 2131.",
		Attributes:  GetDhcpServerSchemaAttributes(ctx),
		Blocks:      GetDhcpServerSchemaBlocks(ctx),
	} // schema

}

// NewDhcpServerResource creates a new instance of the DhcpServer resource.
func NewDhcpServerResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing DhcpServer resource")
	r := &DhcpServerResource{
		ResourceBase: smcresource.ResourceBase[DhcpServerResourceModel]{
			ResourceType:  "dhcp_server",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
