// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Delete_Log_Task
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &DeleteLogTaskResource{}
var _ resource.ResourceWithImportState = &DeleteLogTaskResource{}
var _ context.Context = context.Background()

// DeleteLogTaskResource defines the resource implementation.
type DeleteLogTaskResource struct {
	smcresource.ResourceBase[DeleteLogTaskResourceModel]
}

// Schema defines the schema for the DeleteLogTask resource.
func (r *DeleteLogTaskResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Delete Log Task, which is used to delete logs in the system. It is a type of log task that can be scheduled and executed to ensure that logs are deleted properly.",
		Attributes:  GetDeleteLogTaskSchemaAttributes(ctx),
		Blocks:      GetDeleteLogTaskSchemaBlocks(ctx),
	} // schema

}

// NewDeleteLogTaskResource creates a new instance of the DeleteLogTask resource.
func NewDeleteLogTaskResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing DeleteLogTask resource")
	r := &DeleteLogTaskResource{
		ResourceBase: smcresource.ResourceBase[DeleteLogTaskResourceModel]{
			ResourceType:  "delete_log_task",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
