// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: TLS_Match_Situation
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &TlsMatchSituationResource{}
var _ resource.ResourceWithImportState = &TlsMatchSituationResource{}
var _ context.Context = context.Background()

// TlsMatchSituationResource defines the resource implementation.
type TlsMatchSituationResource struct {
	smcresource.ResourceBase[TlsMatchSituationResourceModel]
}

// Schema defines the schema for the TlsMatchSituation resource.
func (r *TlsMatchSituationResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a TLS Match Situation, which defines matching criteria for the use of the TLS protocol in traffic, allowing you to prevent specified traffic from being decrypted.",
		Attributes:  GetTlsMatchSituationSchemaAttributes(ctx),
		Blocks:      GetTlsMatchSituationSchemaBlocks(ctx),
	} // schema

}

// NewTlsMatchSituationResource creates a new instance of the TlsMatchSituation resource.
func NewTlsMatchSituationResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing TlsMatchSituation resource")
	r := &TlsMatchSituationResource{
		ResourceBase: smcresource.ResourceBase[TlsMatchSituationResourceModel]{
			ResourceType:  "tls_match_situation",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
