// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Layer2_Template_Policy
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &Layer2TemplatePolicyResource{}
var _ resource.ResourceWithImportState = &Layer2TemplatePolicyResource{}
var _ context.Context = context.Background()

// Layer2TemplatePolicyResource defines the resource implementation.
type Layer2TemplatePolicyResource struct {
	smcresource.ResourceBase[Layer2TemplatePolicyResourceModel]
}

// Schema defines the schema for the Layer2TemplatePolicy resource.
func (r *Layer2TemplatePolicyResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Layer 2 Template Policy, which is used to define a set of rules and insert points that can be inherited by other policies or template policies.",
		Attributes:  GetLayer2TemplatePolicySchemaAttributes(ctx),
		Blocks:      GetLayer2TemplatePolicySchemaBlocks(ctx),
	} // schema

}

// NewLayer2TemplatePolicyResource creates a new instance of the Layer2TemplatePolicy resource.
func NewLayer2TemplatePolicyResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing Layer2TemplatePolicy resource")
	r := &Layer2TemplatePolicyResource{
		ResourceBase: smcresource.ResourceBase[Layer2TemplatePolicyResourceModel]{
			ResourceType:  "layer2_template_policy",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
