// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Application_Access_Icon_File
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ApplicationAccessIconFileResource{}
var _ resource.ResourceWithImportState = &ApplicationAccessIconFileResource{}
var _ context.Context = context.Background()

// ApplicationAccessIconFileResource defines the resource implementation.
type ApplicationAccessIconFileResource struct {
	smcresource.ResourceBase[ApplicationAccessIconFileResourceModel]
}

// Schema defines the schema for the ApplicationAccessIconFile resource.
func (r *ApplicationAccessIconFileResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This is an Application Access Icon File. It represents an icon file used in the Application Access interface, typically for visual representation of features or functions.",
		Attributes:  GetApplicationAccessIconFileSchemaAttributes(ctx),
		Blocks:      GetApplicationAccessIconFileSchemaBlocks(ctx),
	} // schema

}

// NewApplicationAccessIconFileResource creates a new instance of the ApplicationAccessIconFile resource.
func NewApplicationAccessIconFileResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ApplicationAccessIconFile resource")
	r := &ApplicationAccessIconFileResource{
		ResourceBase: smcresource.ResourceBase[ApplicationAccessIconFileResourceModel]{
			ResourceType:  "application_accecss_icon_file",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
