// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code NOT generated by tfsmcgen
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &AttrResource{}
var _ resource.ResourceWithImportState = &AttrResource{}
var _ context.Context = context.Background()

type AttrResourceModel struct{}
type AttrResource struct {
	smcresource.ResourceBase[AttrResourceModel]
}

func (r *AttrResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "fake resource. do not use",
	} // schema

}

func NewAttrResource() resource.Resource {
	r := &AttrResource{
		ResourceBase: smcresource.ResourceBase[AttrResourceModel]{
			ResourceType: "attr",
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
