// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Geolocation
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &GeolocationResource{}
var _ resource.ResourceWithImportState = &GeolocationResource{}
var _ context.Context = context.Background()

// GeolocationResource defines the resource implementation.
type GeolocationResource struct {
	smcresource.ResourceBase[GeolocationResourceModel]
}

// Schema defines the schema for the Geolocation resource.
func (r *GeolocationResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents the definition of a geolocation. A Geolocation object keeps a list of Network Elements belonging to the same geolocation.",
		Attributes:  GetGeolocationSchemaAttributes(ctx),
		Blocks:      GetGeolocationSchemaBlocks(ctx),
	} // schema

}

// NewGeolocationResource creates a new instance of the Geolocation resource.
func NewGeolocationResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing Geolocation resource")
	r := &GeolocationResource{
		ResourceBase: smcresource.ResourceBase[GeolocationResourceModel]{
			ResourceType:  "geolocation",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
