// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Virtual_IPS
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &VirtualIpsResource{}
var _ resource.ResourceWithImportState = &VirtualIpsResource{}
var _ context.Context = context.Background()

// VirtualIpsResource defines the resource implementation.
type VirtualIpsResource struct {
	smcresource.ResourceBase[VirtualIpsResourceModel]
}

// Schema defines the schema for the VirtualIps resource.
func (r *VirtualIpsResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Virtual IPS, which is a logically-separate IPS engine that runs as a virtual IPS instance on a Master NGFW Engine. It includes attributes for DNS elements, log buffer size, and various protection modes.",
		Attributes:  GetVirtualIpsSchemaAttributes(ctx),
		Blocks:      GetVirtualIpsSchemaBlocks(ctx),
	} // schema

}

// NewVirtualIpsResource creates a new instance of the VirtualIps resource.
func NewVirtualIpsResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing VirtualIps resource")
	r := &VirtualIpsResource{
		ResourceBase: smcresource.ResourceBase[VirtualIpsResourceModel]{
			ResourceType:  "virtual_ips",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}

var _ resource.ResourceWithValidateConfig = &VirtualIpsResource{}

func (r *VirtualIpsResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data VirtualIpsResourceModel
	// Config.Get fails when any attribute is unknown (e.g. a module output that has
	// not been resolved yet).  In that case we skip sub-validation; the framework
	// will call ValidateConfig again once all values are known.
	if diags := req.Config.Get(ctx, &data); diags.HasError() {
		return
	}
	r.validatePhysicalInterfaces(data, resp)
	r.validateTests(data, resp)
}

func (r *VirtualIpsResource) validatePhysicalInterfaces(data VirtualIpsResourceModel, resp *resource.ValidateConfigResponse) {
	if data.PhysicalInterfaces != nil {
		for _i0, _v0 := range *data.PhysicalInterfaces {
			smcresource.ValidateAnyOf(&_v0, fmt.Sprintf("physical_interfaces[%d]", _i0), &resp.Diagnostics)
			if _v0.PhysicalInterface != nil {
				if _v0.PhysicalInterface.Interfaces != nil {
					for _i1, _v1 := range *_v0.PhysicalInterface.Interfaces {
						smcresource.ValidateAnyOf(&_v1, fmt.Sprintf("physical_interfaces[%d].physical_interface.interfaces[%d]", _i0, _i1), &resp.Diagnostics)
					}
				}
			}
			if _v0.AdslInterface != nil {
				if _v0.AdslInterface.Interfaces != nil {
					for _i1, _v1 := range *_v0.AdslInterface.Interfaces {
						smcresource.ValidateAnyOf(&_v1, fmt.Sprintf("physical_interfaces[%d].adsl_interface.interfaces[%d]", _i0, _i1), &resp.Diagnostics)
					}
				}
			}
			if _v0.PortGroupInterface != nil {
				if _v0.PortGroupInterface.Interfaces != nil {
					for _i1, _v1 := range *_v0.PortGroupInterface.Interfaces {
						smcresource.ValidateAnyOf(&_v1, fmt.Sprintf("physical_interfaces[%d].port_group_interface.interfaces[%d]", _i0, _i1), &resp.Diagnostics)
					}
				}
			}
			if _v0.WirelessInterface != nil {
				if _v0.WirelessInterface.Interfaces != nil {
					for _i1, _v1 := range *_v0.WirelessInterface.Interfaces {
						smcresource.ValidateAnyOf(&_v1, fmt.Sprintf("physical_interfaces[%d].wireless_interface.interfaces[%d]", _i0, _i1), &resp.Diagnostics)
					}
				}
			}
			if _v0.SwitchInterface != nil {
				if _v0.SwitchInterface.Interfaces != nil {
					for _i1, _v1 := range *_v0.SwitchInterface.Interfaces {
						smcresource.ValidateAnyOf(&_v1, fmt.Sprintf("physical_interfaces[%d].switch_interface.interfaces[%d]", _i0, _i1), &resp.Diagnostics)
					}
				}
			}
			if _v0.TunnelInterface != nil {
				if _v0.TunnelInterface.Interfaces != nil {
					for _i1, _v1 := range *_v0.TunnelInterface.Interfaces {
						smcresource.ValidateAnyOf(&_v1, fmt.Sprintf("physical_interfaces[%d].tunnel_interface.interfaces[%d]", _i0, _i1), &resp.Diagnostics)
					}
				}
			}
			if _v0.ModemInterface != nil {
				if _v0.ModemInterface.Interfaces != nil {
					for _i1, _v1 := range *_v0.ModemInterface.Interfaces {
						smcresource.ValidateAnyOf(&_v1, fmt.Sprintf("physical_interfaces[%d].modem_interface.interfaces[%d]", _i0, _i1), &resp.Diagnostics)
					}
				}
			}
			if _v0.VirtualVlanInterface != nil {
				if _v0.VirtualVlanInterface.Interfaces != nil {
					for _i1, _v1 := range *_v0.VirtualVlanInterface.Interfaces {
						smcresource.ValidateAnyOf(&_v1, fmt.Sprintf("physical_interfaces[%d].virtual_vlan_interface.interfaces[%d]", _i0, _i1), &resp.Diagnostics)
					}
				}
			}
			if _v0.VlanInterface != nil {
				if _v0.VlanInterface.Interfaces != nil {
					for _i1, _v1 := range *_v0.VlanInterface.Interfaces {
						smcresource.ValidateAnyOf(&_v1, fmt.Sprintf("physical_interfaces[%d].vlan_interface.interfaces[%d]", _i0, _i1), &resp.Diagnostics)
					}
				}
			}
			if _v0.SsidInterface != nil {
				if _v0.SsidInterface.Interfaces != nil {
					for _i1, _v1 := range *_v0.SsidInterface.Interfaces {
						smcresource.ValidateAnyOf(&_v1, fmt.Sprintf("physical_interfaces[%d].ssid_interface.interfaces[%d]", _i0, _i1), &resp.Diagnostics)
					}
				}
			}
			if _v0.ApnInterface != nil {
				if _v0.ApnInterface.Interfaces != nil {
					for _i1, _v1 := range *_v0.ApnInterface.Interfaces {
						smcresource.ValidateAnyOf(&_v1, fmt.Sprintf("physical_interfaces[%d].apn_interface.interfaces[%d]", _i0, _i1), &resp.Diagnostics)
					}
				}
			}
		}
	}
}

func (r *VirtualIpsResource) validateTests(data VirtualIpsResourceModel, resp *resource.ValidateConfigResponse) {
	if data.Tests != nil {
		for _i0, _v0 := range *data.Tests {
			smcresource.ValidateAnyOf(&_v0, fmt.Sprintf("tests[%d]", _i0), &resp.Diagnostics)
		}
	}
}
