// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: VSS_Container_Node
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &VssContainerNodeResource{}
var _ resource.ResourceWithImportState = &VssContainerNodeResource{}
var _ context.Context = context.Background()

// VssContainerNodeResource defines the resource implementation.
type VssContainerNodeResource struct {
	smcresource.ResourceBase[VssContainerNodeResourceModel]
}

// Schema defines the schema for the VssContainerNode resource.
func (r *VssContainerNodeResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an individual VSS Container Engine node in the Security Management Client, which is a device that runs firewall software as part of a VSS Container.",
		Attributes:  GetVssContainerNodeSchemaAttributes(ctx),
		Blocks:      GetVssContainerNodeSchemaBlocks(ctx),
	} // schema

}

// NewVssContainerNodeResource creates a new instance of the VssContainerNode resource.
func NewVssContainerNodeResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing VssContainerNode resource")
	r := &VssContainerNodeResource{
		ResourceBase: smcresource.ResourceBase[VssContainerNodeResourceModel]{
			ResourceType:  "vss_container_node",
			IsSubResource: true,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}

var _ resource.ResourceWithValidateConfig = &VssContainerNodeResource{}

func (r *VssContainerNodeResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data VssContainerNodeResourceModel
	// Config.Get fails when any attribute is unknown (e.g. a module output that has
	// not been resolved yet).  In that case we skip sub-validation; the framework
	// will call ValidateConfig again once all values are known.
	if diags := req.Config.Get(ctx, &data); diags.HasError() {
		return
	}
	r.validateTests(data, resp)
}

func (r *VssContainerNodeResource) validateTests(data VssContainerNodeResourceModel, resp *resource.ValidateConfigResponse) {
	if data.Tests != nil {
		for _i0, _v0 := range *data.Tests {
			smcresource.ValidateAnyOf(&_v0, fmt.Sprintf("tests[%d]", _i0), &resp.Diagnostics)
		}
	}
}
