// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Application_Access_SSO_Domain
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &ApplicationAccessSsoDomainResource{}
var _ resource.ResourceWithImportState = &ApplicationAccessSsoDomainResource{}
var _ context.Context = context.Background()

// ApplicationAccessSsoDomainResource defines the resource implementation.
type ApplicationAccessSsoDomainResource struct {
	smcresource.ResourceBase[ApplicationAccessSsoDomainResourceModel]
}

// Schema defines the schema for the ApplicationAccessSsoDomain resource.
func (r *ApplicationAccessSsoDomainResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents an Application Access Single Sign On Domain, which includes properties such as SSO mode and timeout settings.",
		Attributes:  GetApplicationAccessSsoDomainSchemaAttributes(ctx),
		Blocks:      GetApplicationAccessSsoDomainSchemaBlocks(ctx),
	} // schema

}

// NewApplicationAccessSsoDomainResource creates a new instance of the ApplicationAccessSsoDomain resource.
func NewApplicationAccessSsoDomainResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing ApplicationAccessSsoDomain resource")
	r := &ApplicationAccessSsoDomainResource{
		ResourceBase: smcresource.ResourceBase[ApplicationAccessSsoDomainResourceModel]{
			ResourceType:  "application_access_sso_domain",
			IsSubResource: false,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
