// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: VSS_Context_Node
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &VssContextNodeResource{}
var _ resource.ResourceWithImportState = &VssContextNodeResource{}
var _ context.Context = context.Background()

// VssContextNodeResource defines the resource implementation.
type VssContextNodeResource struct {
	smcresource.ResourceBase[VssContextNodeResourceModel]
}

// Schema defines the schema for the VssContextNode resource.
func (r *VssContextNodeResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a VSS Context Engine node in the Security Management Client, which is a virtual device that runs firewall software as part of a VSS Container.",
		Attributes:  GetVssContextNodeSchemaAttributes(ctx),
		Blocks:      GetVssContextNodeSchemaBlocks(ctx),
	} // schema

}

// NewVssContextNodeResource creates a new instance of the VssContextNode resource.
func NewVssContextNodeResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing VssContextNode resource")
	r := &VssContextNodeResource{
		ResourceBase: smcresource.ResourceBase[VssContextNodeResourceModel]{
			ResourceType:  "vss_context_node",
			IsSubResource: true,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
