// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Layer2_IPv4_Access_Rule
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &Layer2Ipv4AccessRuleResource{}
var _ resource.ResourceWithImportState = &Layer2Ipv4AccessRuleResource{}
var _ context.Context = context.Background()

// Layer2Ipv4AccessRuleResource defines the resource implementation.
type Layer2Ipv4AccessRuleResource struct {
	smcresource.ResourceBase[Layer2Ipv4AccessRuleResourceModel]
}

// Schema defines the schema for the Layer2Ipv4AccessRule resource.
func (r *Layer2Ipv4AccessRuleResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a Firewall Layer 2 IPv4 Access Rule. It defines how one type of IPv4 connection is handled by providing matching criteria based on the source, destination, and protocol information.",
		Attributes:  GetLayer2Ipv4AccessRuleSchemaAttributes(ctx),
		Blocks:      GetLayer2Ipv4AccessRuleSchemaBlocks(ctx),
	} // schema

}

// NewLayer2Ipv4AccessRuleResource creates a new instance of the Layer2Ipv4AccessRule resource.
func NewLayer2Ipv4AccessRuleResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing Layer2Ipv4AccessRule resource")
	r := &Layer2Ipv4AccessRuleResource{
		ResourceBase: smcresource.ResourceBase[Layer2Ipv4AccessRuleResourceModel]{
			ResourceType:  "layer2_ipv4_access_rule",
			IsSubResource: true,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}

// special case for rank attribute
func (r *Layer2Ipv4AccessRuleResource) getCreateRequestParams(_ context.Context, data *Layer2Ipv4AccessRuleResourceModel) (map[string]string, error) {
	if !data.Rank.IsNull() && !data.Rank.IsUnknown() {
		queryParams := map[string]string{
			"keep_specified_rank": "true",
		}
		return queryParams, nil
	}
	return nil, nil
}
