// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: VPN_Site
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/config"
	smcresource "github.com/terraform-providers/terraform-provider-smc/internal/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &VpnSiteResource{}
var _ resource.ResourceWithImportState = &VpnSiteResource{}
var _ context.Context = context.Background()

// VpnSiteResource defines the resource implementation.
type VpnSiteResource struct {
	smcresource.ResourceBase[VpnSiteResourceModel]
}

// Schema defines the schema for the VpnSite resource.
func (r *VpnSiteResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	use_hcl2, err := config.IsHcl2Enabled(common.PROVIDER_TYPE_NAME + "_" + r.ResourceType)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting HCL2 setting",
			err.Error(),
		)
		return
	}

	ctx = context.WithValue(ctx, "use_hcl2", use_hcl2)
	resp.Schema = schema.Schema{
		Description: "This represents a VPN Site, which is a collection of network elements that are part of a VPN. It can be associated with a gateway and has references to VPNs.",
		Attributes:  GetVpnSiteSchemaAttributes(ctx),
		Blocks:      GetVpnSiteSchemaBlocks(ctx),
	} // schema

}

// NewVpnSiteResource creates a new instance of the VpnSite resource.
func NewVpnSiteResource() resource.Resource {
	tflog.Debug(context.Background(), "Initializing VpnSite resource")
	r := &VpnSiteResource{
		ResourceBase: smcresource.ResourceBase[VpnSiteResourceModel]{
			ResourceType:  "vpn_site",
			IsSubResource: true,
		},
	}
	r.ResourceBase.Dispatch = r
	return r
}
