// Copyright 2026 Forcepoint LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package schema

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/terraform-providers/terraform-provider-smc/internal/common"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ = (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = float64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue

func GetAdvancedMultiLinkSettingsSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	useHcl2 := common.UseHCL2(ctx)

	attrs := map[string]schema.Attribute{"activate_failover": schema.Int64Attribute{
		Optional:    true,
		Description: "The time in seconds to activate failover after the threshold is reached.",
	},
		"dpd_initial_values": schema.StringAttribute{
			Optional:    true,
			Description: "The initial values for DPD (Dead Peer Detection) settings, which can be used to configure the initial state of the Multi-Link.",
		},
		"failover_initial_values": schema.StringAttribute{
			Optional:    true,
			Description: "The initial values for failover settings, which can be used to configure the initial state of the Multi-Link.",
		},
		"failover_prop_high": schema.Int64Attribute{
			Optional:    true,
			Description: "The failover property high, which is a percentage value that indicates the threshold for high failover conditions.",
		},
		"failover_threshold": schema.Int64Attribute{
			Optional:    true,
			Description: "The failover threshold, which determines the number of failed probes before a failover is triggered.",
		},
		"in_traffic_initial_values": schema.StringAttribute{
			Optional:    true,
			Description: "The initial values for in-traffic settings, which can be used to configure the initial state of the Multi-Link.",
		},
		"latency_initial_values": schema.StringAttribute{
			Optional:    true,
			Description: "The initial values for latency settings, which can be used to configure the initial state of the Multi-Link.",
		},
		"multilink_extra_options": schema.StringAttribute{
			Optional:    true,
			Description: "Additional options for Multi-Link settings, which can be used to configure extra parameters for the Multi-Link.",
		},
		"pdr_initial_values": schema.StringAttribute{
			Optional:    true,
			Description: "The initial values for PDR (Packet Delivery Ratio) settings, which can be used to configure the initial state of the Multi-Link.",
		},
		"probe_threshold": schema.Int64Attribute{
			Optional:    true,
			Description: "The probe threshold, which is a percentage value that indicates the threshold for probing the links.",
		},
		"remoteload_initial_values": schema.StringAttribute{
			Optional:    true,
			Description: "The initial values for remote load settings, which can be used to configure the initial state of the Multi-Link.",
		},
		"throughput_initial_values": schema.StringAttribute{
			Optional:    true,
			Description: "The initial values for throughput settings, which can be used to configure the initial state of the Multi-Link.",
		},
	}
	if !useHcl2 {
		return attrs
	}

	blocks := getAdvancedMultiLinkSettingsSchemaBlocksInternal(ctx)
	extra_attrs := common.ConvertToHCL2(ctx, attrs, blocks)
	return extra_attrs
}

func GetAdvancedMultiLinkSettingsSchemaBlocks(ctx context.Context) map[string]schema.Block {
	useHcl2 := common.UseHCL2(ctx)
	if useHcl2 {
		return map[string]schema.Block{}
	}
	return getAdvancedMultiLinkSettingsSchemaBlocksInternal(ctx)
}

func getAdvancedMultiLinkSettingsSchemaBlocksInternal(ctx context.Context) map[string]schema.Block {
	max_recursion_val := ctx.Value("max_recursion")
	if max_recursion_val != nil {
		max_recursion, ok := max_recursion_val.(int)
		if ok && max_recursion <= 0 {
			return map[string]schema.Block{}
		}
		ctx = context.WithValue(ctx, "max_recursion", max_recursion-1)
	}
	return map[string]schema.Block{}
}
